---
- hosts: localhost
  vars:
    container_name: websvr03
    container_path: /hdd2/VMs/lxc

  remote_user: root

  tasks:
  - name: Create a new container and clone it
    lxc_container:
      name: TEMPLATE_Ubuntu_16.04
      backing_store: dir
      clone_name: websvr04

#  - name: Create a started container
#    lxc_container:
#      name: "{{ container_name }}"
#      container_log: true
#      template: download
#      state: started
#      template_options: -d ubuntu -r trusty -a amd64

#  - name: waiting
#    pause: seconds=15
#      prompt="Shits starting. Wait....."


#      /usr/bin/lxc-attach -n websvr02 -- apt-get update && apt-get -y install openssh-server

#    ignore_errors: false
#    tags:
#      - debug

# FOR A FEDORA CONTAINER
#  - name: Create a started container
#    lxc_container:
#      name: websvr01
##      container_log: true
#      template: fedora
#      state: started
#      template_options: --release 25

#- name: chroot passwd

#  - name: Instrall nginx
#    yum: pkg=nginx state=installed
#    tags:
#      - nginx
#      - debug