---
- hosts: ans01
  remote_user: root
  tasks:
  - name: Enable and start NGINX
    service: name=nginx.service state=started enabled=yes

- hosts: ans02
	remote_user: root
	tasks:
	- name: Power off a server
	lxc_container:
		name: Ansible02_ubuntu:
		state: stopped